global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'stockflaskapplication'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'https://stockflaskapplication-22a2f4752d69.herokuapp.com' ]
